
name: 3-tier-Application

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - name: Build & test backend
              working-directory: api
              run: |
                dotnet restore 
                dotnet build
                dotnet test
                dotnet pack
    


